/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
usage: train.py [-h] -opt OPT [--launcher {none,pytorch,slurm}]
                [--auto_resume] [--debug] [--local_rank LOCAL_RANK]
                [--force_yml FORCE_YML [FORCE_YML ...]]
train.py: error: unrecognized arguments: --local-rank=0
[2024-04-25 16:41:33,338] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 59020) of binary: /home/msai/bugn0001/.conda/envs/acv-swinfir/bin/python
Traceback (most recent call last):
  File "/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/msai/bugn0001/.conda/envs/acv-swinfir/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
swinfir/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-25_16:41:33
  host      : SCSEGPU-TC2-01.cm.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 59020)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
